services:
  - type: web
    name: superputin-platform-backend
    env: node
    plan: free
    buildCommand: |
      export NODE_OPTIONS="--max-old-space-size=512" && npm install
      export NODE_OPTIONS="--max-old-space-size=512" && npm run build
    startCommand: node --optimize-for-size --max-old-space-size=64 dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URL
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_PUBLIC_URL
        value: https://pub-d428e22145884a3e9e1719f9807f326f.r2.dev
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1