services:
  - type: web
    name: superputin-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET
        sync: false
      - key: AWS_REGION
        sync: false
    autoDeploy: true
    healthCheckPath: /api/test
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 