services:
  - type: web
    name: superputin-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://superputin.onrender.com

  - type: static
    name: superputin-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://superputin-backend.onrender.com