services:
  - type: web
    name: superputin-platform-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URL
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_PUBLIC_URL
        value: https://pub-d428e22145884a3e9e1719f9807f326f.r2.dev
    autoDeploy: true
    healthCheckPath: /api/test
    disk:
      name: uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1